//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LUSerParamX.rc
//
#define IDS_LUSERPARAMX                 1
#define IDB_LUSERPARAMX                 1
#define IDS_LUSERPARAMX_PPG             2
#define IDS_LUSERPARAMX_PPG_CAPTION     200
#define IDD_PROPPAGE_LUSERPARAMX        200
#define IDD_DLG_PARAM                   201
#define IDC_TREEFUN                     201
#define IDS_STRING201                   201
#define IDS_STRING202                   202
#define IDC_STATIC_INFO                 202
#define IDD_DLG_SERGOBAL                202
#define IDS_STRING203                   203
#define IDC_STATIC_DLG                  203
#define IDS_STRING204                   204
#define IDC_BTN_GET                     204
#define IDD_DLG_SERNET                  204
#define IDS_STRING205                   205
#define IDC_BTN_SET                     205
#define IDS_STRING206                   206
#define IDC_CHECK1                      206
#define IDD_DLG_SERUSER                 206
#define IDC_BTN_GET2                    206
#define IDC_CHECK_USEWIFI               206
#define IDC_CHECK_AREA1                 206
#define IDS_STRING207                   207
#define IDC_DATETIMEPICKER1             207
#define IDD_DLG_CHENCPARAM              207
#define IDC_BTN_SET2                    207
#define IDC_CHECK_USECDMA               207
#define IDS_STRING208                   208
#define IDC_COMBO1                      208
#define IDC_COMBO_MODE                  208
#define IDC_COMBO_DISK                  208
#define IDC_COMBO_WEP                   208
#define IDS_STRING209                   209
#define IDC_BUTTON1                     209
#define IDC_BTN_FORMAT                  209
#define IDS_STRING210                   210
#define IDC_COMBO2                      210
#define IDD_DLG_CHOSD                   210
#define IDC_BTN_RESET                   210
#define IDS_STRING211                   211
#define IDC_BUTTON2                     211
#define IDS_STRING212                   212
#define IDD_DLG_CHMOTIONAREA            212
#define IDC_BTN_DEFAULT                 212
#define IDS_STRING213                   213
#define IDC_EDIT_BRI                    213
#define IDS_STRING214                   214
#define IDD_DLG_CHMOTIONTIME            214
#define IDC_BTN_UPDATE                  214
#define IDC_EDIT_CON                    214
#define IDS_STRING215                   215
#define IDD_DLG_CHRECVTIME              215
#define IDC_DATE_SYNCTIME               215
#define IDC_EDIT_SAT                    215
#define IDS_STRING216                   216
#define IDD_DLG_CHVMASK                 216
#define IDC_BTN_SYNCTIME1               216
#define IDC_EDIT_HUE                    216
#define IDS_STRING217                   217
#define IDD_DLG_CHVPARAM                217
#define IDC_CHECK_TIMERESET             217
#define IDC_BTN_SYNCTIME2               217
#define IDS_STRING218                   218
#define IDS_STRING219                   219
#define IDD_DLG_CHVHIDE                 219
#define IDC_STATIC_CURTIME              219
#define IDS_STRING220                   220
#define IDD_DLG_CHVLOST                 220
#define IDC_BTN_SELFILE                 220
#define IDS_STRING221                   221
#define IDD_DLG_CHJPEGPARA              221
#define IDC_BTN_SAVE                    221
#define IDD_DLG_CHPTZ                   222
#define IDS_STRING222                   222
#define IDC_DATE_SYNCDATE               222
#define IDD_DLG_ALARM                   223
#define IDS_STRING223                   223
#define IDC_EDIT_FILE                   223
#define IDD_DLG_SERDISK                 224
#define IDS_STRING224                   224
#define IDC_PROGRESS1                   224
#define IDS_STRING225                   225
#define IDC_BTN_COPY1                   225
#define IDS_STRING226                   226
#define IDC_BTN_COPY2                   226
#define IDS_STRING227                   227
#define IDC_COMBO_CHCOPY1               227
#define IDS_STRING228                   228
#define IDC_COMBO_CHCOPY2               228
#define IDS_STRING229                   229
#define IDS_STRING230                   230
#define IDC_STATIC_COPY1                230
#define IDS_STRING231                   231
#define IDC_STATIC_COPY2                231
#define IDS_STRING232                   232
#define IDD_DLG_SERSAVE                 233
#define IDS_STRING233                   233
#define IDS_STRING234                   234
#define IDD_DLG_SERUPDATE               234
#define IDC_CHECK_AUTOTREC              234
#define IDS_STRING235                   235
#define IDC_STATIC_CALLCH               235
#define IDD_DLG_FORMATDISK              235
#define IDS_STRING236                   236
#define IDC_EDIT_SENNAME                236
#define IDD_DLG_AUDIOPARAM              236
#define IDS_STRING237                   237
#define IDC_STATIC_DISK                 237
#define IDC_EDIT_INTERTIME              237
#define IDS_STRING238                   238
#define IDC_STATIC_VAL                  238
#define IDD_DLG_WIRELESS                238
#define IDS_STRING239                   239
#define IDC_CHECK_EN                    239
#define IDS_STRING240                   240
#define IDD_DLG_HUMITUREPRAM            240
#define IDS_STRING241                   241
#define IDC_EDIT_LINEIN                 241
#define IDS_STRING242                   242
#define IDC_COMBO_MIC                   242
#define IDD_DLG_EXALARMPARAM            242
#define IDS_STRING243                   243
#define IDC_EDIT_AUDIOOUT               243
#define IDS_STRING244                   244
#define IDC_EDIT_TEMPMAX                244
#define IDS_STRING245                   245
#define IDC_EDIT_TEMPMIN                245
#define IDS_STRING246                   246
#define IDC_EDIT_HUMMAX                 246
#define IDS_STRING247                   247
#define IDC_EDIT_HUMMIN                 247
#define IDS_STRING248                   248
#define IDC_EDIT_DELAYTIME              248
#define IDS_STRING249                   249
#define IDC_EDIT_ADDR                   249
#define IDS_STRING250                   250
#define IDC_RADIO_AREA1                 250
#define IDS_STRING251                   251
#define IDC_RADIO_AREA2                 251
#define IDS_STRING252                   252
#define IDC_RADIO_AREA3                 252
#define IDS_STRING253                   253
#define IDC_RADIO_AREA4                 253
#define IDS_STRING254                   254
#define IDS_STRING255                   255
#define IDS_STRING256                   256
#define IDS_STRING257                   257
#define IDS_STRING258                   258
#define IDS_STRING259                   259
#define IDS_STRING260                   260
#define IDS_STRING261                   261
#define IDS_STRING262                   262
#define IDS_STRING263                   263
#define IDS_STRING264                   264
#define IDS_STRING265                   265
#define IDS_STRING266                   266
#define IDS_STRING267                   267
#define IDS_STRING268                   268
#define IDS_STRING269                   269
#define IDS_STRING270                   270
#define IDS_STRING271                   271
#define IDS_STRING272                   272
#define IDS_STRING273                   273
#define IDS_STRING274                   274
#define IDS_STRING275                   275
#define IDS_STRING276                   276
#define IDS_STRING277                   277
#define IDS_STRING278                   278
#define IDS_STRING279                   279
#define IDS_STRING280                   280
#define IDS_STRING281                   281
#define IDS_STRING282                   282
#define IDS_STRING283                   283
#define IDS_STRING284                   284
#define IDS_STRING285                   285
#define IDS_STRING286                   286
#define IDS_STRING287                   287
#define IDS_STRING288                   288
#define IDS_STRING289                   289
#define IDS_STRING290                   290
#define IDC_COMBO_ISPAL                 1051
#define IDC_COMBO_LAUNAGE               1052
#define IDC_EDIT_NAME                   1053
#define IDC_EDIT_IP                     1054
#define IDC_EDIT_DEVICEID               1054
#define IDC_EDIT_SUBMASK                1055
#define IDC_EDIT_MAXCONNECT             1055
#define IDC_EDIT_DNS                    1056
#define IDC_EDIT_DEVICEMODEL            1056
#define IDC_EDIT_GETWAY                 1057
#define IDC_COMBO_LINKTYPE              1057
#define IDC_EDIT_MULTIIP                1058
#define IDC_EDIT_SSID                   1058
#define IDC_EDIT_FTPUSER                1058
#define IDC_EDIT_SERPORT                1059
#define IDC_EDIT_PASSWORD               1059
#define IDC_EDIT_FTPPASS                1059
#define IDC_EDIT_MULTIPORT              1060
#define IDC_EDIT_SIPPORT                1060
#define IDC_EDIT_WEBPORT                1061
#define IDC_COMBO_USEDDNS               1062
#define IDC_EDIT_MAC                    1063
#define IDC_EDIT_DDNSIP                 1064
#define IDC_EDIT_DDNSPORT               1065
#define IDC_EDIT_DDNSMAPPORT            1066
#define IDC_COMBO_DISLDELTYPE           1067
#define IDC_COMBO_DDNSPROVIDER          1067
#define IDC_COMBO_PPPOE                 1068
#define IDC_EDIT_DDNSUSERNAME           1069
#define IDC_EDIT_DDNSPASS               1070
#define IDC_EDIT_DDNSTIME               1071
#define IDC_EDIT_DDNSNAME               1072
#define IDC_EDIT_VERSION                1073
#define IDC_EDIT_VERTIME                1074
#define IDC_EDIT_ALARMURL               1075
#define IDC_EDIT_ALARMPORT              1077
#define IDC_STREAMTYPE                  1077
#define IDC_EDIT_REHOSTURL              1078
#define IDC_IKEYINTERVAL                1078
#define IDC_EDIT_REHOSTPORT             1079
#define IDC_MAXRATE                     1079
#define IDC_EDIT_PPPOEUSER              1080
#define IDC_MINQUEUE                    1080
#define IDC_EDIT_PPPOEPASS              1081
#define IDC_FRAMERATE                   1081
#define IDC_EDIT_SERIALNO               1082
#define IDC_MAXQUEUE                    1082
#define IDC_BITRATETYPE                 1083
#define IDC_SAMPLERATE                  1084
#define IDC_AUBITS                      1085
#define IDC_IMAGEFORMAT                 1086
#define IDC_CHECK_BITSOSD               1087
#define IDC_EDIT_QUANT                  1087
#define IDC_SUBSTREAMTYPE               1088
#define IDC_BITOSD_X                    1088
#define IDC_EDIT_RATE                   1088
#define IDC_SUBIKEYINTERVAL             1089
#define IDC_BITOSD_Y                    1089
#define IDC_SUBMAXRATE                  1090
#define IDC_TIMEOSD                     1090
#define IDC_EDIT_TOTAL                  1090
#define IDC_SUBMINQUEUE                 1091
#define IDC_TIMEOSD_X                   1091
#define IDC_SUBFRAMERATE                1092
#define IDC_TIMEOSD_Y                   1092
#define IDC_SUBMAXQUEUE                 1093
#define IDC_TITALOSD1                   1093
#define IDC_SUBBITRATETYPE              1094
#define IDC_TITALOSD1_X                 1094
#define IDC_SUBIMAGEFORMAT              1095
#define IDC_TITALOSD1_Y                 1095
#define IDC_TITALOSD2                   1096
#define IDC_DELAY                       1097
#define IDC_TITALOSD2_X                 1099
#define IDC_TITALOSD2_Y                 1100
#define IDC_TITALOSD3                   1101
#define IDC_TITALOSD3_X                 1102
#define IDC_TITALOSD3_Y                 1103
#define IDC_TITALOSD4                   1104
#define IDC_COMBO_FORMAT                1104
#define IDC_TITALOSD4_X                 1105
#define IDC_COMBO_TYPE                  1105
#define IDC_TITALOSD4_Y                 1106
#define IDC_CHECK_ON                    1108
#define IDC_PRERECTIME                  1118
#define IDC_VIDEOOFFSET                 1119
#define IDC_COMBO_PTZCHSEL              1126
#define IDC_CHECK_PTZCALL               1127
#define IDC_EDIT_PTZNO                  1128
#define IDC_ADDR                        1129
#define IDC_EDIT_PTZNAME                1130
#define IDC_EDIT_ALARMTIME              1130
#define IDC_EDIT_PTZFILE                1131
#define IDC_EDIT_CHECKTIME              1131
#define IDC_BTN_FILE                    1132
#define IDC_BTN_PTZFILESET              1133
#define IDC_EDIT_ADMINUSR               1137
#define IDC_EDIT_ADMINPASS              1138
#define IDC_SLIDER_MOTIONAREA           1166
#define IDC_BTN_ALL                     1168
#define IDC_BTN_CLEAN                   1169
#define IDC_CHECK_TEST                  1170
#define IDC_STATIC_WND                  1177
#define IDC_BITRATE                     1177
#define IDC_DATABIT                     1178
#define IDC_SLIDER_BRI                  1178
#define IDC_STOPBIT                     1179
#define IDC_SLIDER_CON                  1179
#define IDC_CHECKBIT                    1180
#define IDC_SLIDER_SAT                  1180
#define IDC_SLIDER_HUE                  1181
#define IDC_COMBO_PROTOCOL              1181
#define IDC_COMBO_COMPORT               1182
#define IDC_STATIC_REC                  1183
#define IDC_STATIC_OUTPUT               1184
#define IDC_STATIC_CAPJPEG              1185
#define IDC_STATIC_ALARMHOST            1186
#define IDC_CHECK_RECV1                 4000
#define IDC_CHECK_RECV2                 4001
#define IDC_CHECK_RECV3                 4002
#define IDC_CHECK_RECV4                 4003
#define IDC_CHECK_ALARMOUT1             4004
#define IDC_CHECK_ALARMOUT2             4005
#define IDC_CHECK_ALARMOUT3             4006
#define IDC_CHECK_ALARMOUT4             4007
#define IDC_CHECK_CAPJPEG1              4008
#define IDC_CHECK_CAPJPEG2              4009
#define IDC_CHECK_CAPJPEG3              4010
#define IDC_CHECK_CAPJPEG4              4011
#define IDC_COMBO_TIME1                 4012
#define IDC_COMBO_TIME2                 4013
#define IDC_COMBO_TIME3                 4014
#define IDC_COMBO_TIME4                 4015
#define IDC_COMBO_TIME5                 4016
#define IDC_COMBO_TIME6                 4017
#define IDC_COMBO_TIME7                 4018
#define IDC_STARTHOUR1                  4019
#define IDC_STARTHOUR2                  4020
#define IDC_STARTHOUR3                  4021
#define IDC_STARTHOUR4                  4022
#define IDC_STARTHOUR5                  4023
#define IDC_STARTHOUR6                  4024
#define IDC_STARTHOUR7                  4025
#define IDC_STARTMINUTE1                4026
#define IDC_STARTMINUTE2                4027
#define IDC_STARTMINUTE3                4028
#define IDC_STARTMINUTE4                4029
#define IDC_STARTMINUTE5                4030
#define IDC_STARTMINUTE6                4031
#define IDC_STARTMINUTE7                4032
#define IDC_STOPHOUR1                   4033
#define IDC_STOPHOUR2                   4034
#define IDC_STOPHOUR3                   4035
#define IDC_STOPHOUR4                   4036
#define IDC_STOPHOUR5                   4037
#define IDC_STOPHOUR6                   4038
#define IDC_STOPHOUR7                   4039
#define IDC_STOPMINUTE1                 4040
#define IDC_STOPMINUTE2                 4041
#define IDC_STOPMINUTE3                 4042
#define IDC_STOPMINUTE4                 4043
#define IDC_STOPMINUTE5                 4044
#define IDC_STOPMINUTE6                 4045
#define IDC_STOPMINUTE7                 4046
#define IDC_CHECK_ALARMTOHOST           4047
#define IDC_STATIC_TYPE1                4050
#define IDC_STATIC_TYPE2                4051
#define IDC_STATIC_TYPE3                4052
#define IDC_STATIC_TYPE4                4053
#define IDC_STATIC_TYPE5                4054
#define IDC_STATIC_TYPE6                4055
#define IDC_STATIC_TYPE7                4056
#define IDC_STATIC_TYPE8                4057
#define IDC_STATIC_TOTALSIZE1           4066
#define IDC_STATIC_TOTALSIZE2           4067
#define IDC_STATIC_TOTALSIZE3           4068
#define IDC_STATIC_TOTALSIZE4           4069
#define IDC_STATIC_TOTALSIZE5           4070
#define IDC_STATIC_TOTALSIZE6           4071
#define IDC_STATIC_TOTALSIZE7           4072
#define IDC_STATIC_TOTALSIZE8           4073
#define IDC_STATIC_FREESIZE1            4074
#define IDC_STATIC_FREESIZE2            4075
#define IDC_STATIC_FREESIZE3            4076
#define IDC_STATIC_FREESIZE4            4077
#define IDC_STATIC_FREESIZE5            4078
#define IDC_STATIC_FREESIZE6            4079
#define IDC_STATIC_FREESIZE7            4080
#define IDC_STATIC_FREESIZE8            4081
#define IDC_STATIC_STAT1                4082
#define IDC_STATIC_STAT2                4083
#define IDC_STATIC_STAT3                4084
#define IDC_STATIC_STAT4                4085
#define IDC_STATIC_STAT5                4086
#define IDC_STATIC_STAT6                4087
#define IDC_STATIC_STAT7                4088
#define IDC_STATIC_STAT8                4089
#define IDC_EDIT_HIOPUSR1               4090
#define IDC_EDIT_HIOPUSR2               4091
#define IDC_EDIT_HIOPUSR3               4092
#define IDC_EDIT_HIOPUSR4               4093
#define IDC_EDIT_HIOPUSR5               4094
#define IDC_EDIT_HIOPUSR6               4095
#define IDC_EDIT_HIOPUSR7               4096
#define IDC_EDIT_HIOPUSR8               4097
#define IDC_EDIT_HIOPUSR9               4098
#define IDC_EDIT_HIOPUSR10              4099
#define IDC_EDIT_HIOPPASS1              4100
#define IDC_EDIT_HIOPPASS2              4101
#define IDC_EDIT_HIOPPASS3              4102
#define IDC_EDIT_HIOPPASS4              4103
#define IDC_EDIT_HIOPPASS5              4104
#define IDC_EDIT_HIOPPASS6              4105
#define IDC_EDIT_HIOPPASS7              4106
#define IDC_EDIT_HIOPPASS8              4107
#define IDC_EDIT_HIOPPASS9              4108
#define IDC_EDIT_HIOPPASS10             4109
#define IDC_EDIT_OPUSR1                 4110
#define IDC_EDIT_OPUSR2                 4111
#define IDC_EDIT_OPUSR3                 4112
#define IDC_EDIT_OPUSR4                 4113
#define IDC_EDIT_OPUSR5                 4114
#define IDC_EDIT_OPUSR6                 4115
#define IDC_EDIT_OPUSR7                 4116
#define IDC_EDIT_OPUSR8                 4117
#define IDC_EDIT_OPUSR9                 4118
#define IDC_EDIT_OPUSR10                4119
#define IDC_EDIT_OPPASS1                4120
#define IDC_EDIT_OPPASS2                4121
#define IDC_EDIT_OPPASS3                4122
#define IDC_EDIT_OPPASS4                4123
#define IDC_EDIT_OPPASS5                4124
#define IDC_EDIT_OPPASS6                4125
#define IDC_EDIT_OPPASS7                4126
#define IDC_EDIT_OPPASS8                4127
#define IDC_EDIT_OPPASS9                4128
#define IDC_EDIT_OPPASS10               4129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        244
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         251
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
